service:
  api:
  image: src.microsoft.com/devcontainers/java:17
    volume: 
    - ../:/workspace:cached
      command: /bin/sh -c "while sleep 1000; do :; done"
        depend_on:
     - db

       db:
          image: postgres:15-alpine
          restart: unless-stopped
          environment:
          POSTGRES_USER: delivery_user
          POSTGRES_PASSWORD: delivery_password

            POSTGRES_DB: delivery_db
              ports:
                    -"5432-5432"
